# Generated by Django 5.2.14 on 2026-05-26 05:37

import django.db.models.deletion
from django.db import migrations, models


def remap_student_ids(apps, schema_editor):
    """
    CheckoutLog.student_id and RoomReservation.student_id previously stored
    User UUIDs. Now they must store Student UUIDs.

    Strategy:
    1. Drop the old FK constraints (they point to users) so the remap UPDATE
       can set student_id to Student UUIDs without violating the constraint.
    2. Remap rows where the old user_id matches a student's user_id.
    3. Delete any remaining rows that can't be remapped (orphaned seed data).

    Django's alter_field will then query the live DB for constraints, find none,
    and only add the new FK pointing to students.
    """
    with schema_editor.connection.cursor() as cursor:
        # Drop old FK constraints dynamically (names are auto-generated by Django)
        for table, col in [
            ("inventory_checkoutlog", "student_id"),
            ("inventory_roomreservation", "student_id"),
        ]:
            cursor.execute(
                """
                SELECT tc.constraint_name
                FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu
                    ON tc.constraint_name = kcu.constraint_name
                    AND tc.table_schema = kcu.table_schema
                WHERE tc.table_name = %s
                  AND tc.constraint_type = 'FOREIGN KEY'
                  AND kcu.column_name = %s
                """,
                [table, col],
            )
            for (name,) in cursor.fetchall():
                cursor.execute(f'ALTER TABLE "{table}" DROP CONSTRAINT IF EXISTS "{name}"')

        # Remap: set student_id = students.id where old value was the student's user_id
        cursor.execute("""
            UPDATE inventory_checkoutlog cl
            SET student_id = s.id
            FROM students s
            WHERE cl.student_id = s.user_id
        """)
        # Delete rows that can't be mapped (user has no student profile or user was deleted)
        cursor.execute("""
            DELETE FROM inventory_checkoutlog
            WHERE student_id NOT IN (SELECT id FROM students)
        """)

        cursor.execute("""
            UPDATE inventory_roomreservation rr
            SET student_id = s.id
            FROM students s
            WHERE rr.student_id = s.user_id
        """)
        cursor.execute("""
            DELETE FROM inventory_roomreservation
            WHERE student_id NOT IN (SELECT id FROM students)
        """)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_user_is_approved"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(remap_student_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="checkoutlog",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_checkouts",
                to="core.student",
            ),
        ),
        migrations.AlterField(
            model_name="roomreservation",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_reservations",
                to="core.student",
            ),
        ),
    ]
