# Generated by Django 5.0.1 on 2026-02-04 21:05

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_create_periodic_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="band",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Band/group photo (max 5MB, JPG/PNG/GIF/WebP)",
                null=True,
                upload_to="bands/",
                validators=[
                    apps.core.validators.FileValidator(
                        allowed_extensions=[".jpg", ".jpeg", ".png", ".gif", ".webp"],
                        max_size=5242880,
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studio",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Studio cover image (max 5MB, JPG/PNG/GIF/WebP)",
                null=True,
                upload_to="studio_covers/",
                validators=[
                    apps.core.validators.FileValidator(
                        allowed_extensions=[".jpg", ".jpeg", ".png", ".gif", ".webp"],
                        max_size=5242880,
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.FileField(
                blank=True,
                help_text="Profile picture (max 5MB, JPG/PNG/GIF/WebP)",
                null=True,
                upload_to="avatars/",
                validators=[
                    apps.core.validators.FileValidator(
                        allowed_extensions=[".jpg", ".jpeg", ".png", ".gif", ".webp"],
                        max_size=5242880,
                    )
                ],
            ),
        ),
    ]
