# Generated by Django 5.2.15 on 2026-06-19 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_alter_notification_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
