# Generated by Django 5.0.1 on 2025-12-29 16:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_alter_student_instrument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, help_text="Unique key for this flag (e.g., 'stripe_payments')", max_length=200, unique=True)),
                ('name', models.CharField(help_text='Human-readable name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of what this flag controls')),
                ('flag_type', models.CharField(choices=[('boolean', 'Boolean'), ('string', 'String'), ('number', 'Number'), ('json', 'JSON')], default='boolean', max_length=20)),
                ('value_boolean', models.BooleanField(blank=True, default=False, null=True)),
                ('value_string', models.TextField(blank=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('studio', 'Studio-Specific'), ('user', 'User-Specific'), ('role', 'Role-Based')], default='global', max_length=20)),
                ('target_roles', models.JSONField(blank=True, default=list, help_text="Roles this flag applies to (if scope=role), e.g., ['admin', 'teacher']")),
                ('category', models.CharField(blank=True, help_text="Category for grouping flags (e.g., 'billing', 'notifications')", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this flag is currently active')),
                ('rollout_percentage', models.IntegerField(default=100, help_text='Percentage of users to enable this flag for (0-100). Uses deterministic hash for consistency.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_flags', to=settings.AUTH_USER_MODEL)),
                ('target_studios', models.ManyToManyField(blank=True, help_text='Studios this flag applies to (if scope=studio)', related_name='feature_flags', to='core.studio')),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'db_table': 'feature_flags',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlagOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value_boolean', models.BooleanField(blank=True, default=False, null=True)),
                ('value_string', models.TextField(blank=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='feature_flags.featureflag')),
                ('studio', models.ForeignKey(blank=True, help_text='Studio this override applies to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flag_overrides', to='core.studio')),
                ('user', models.ForeignKey(blank=True, help_text='User this override applies to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flag_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Flag Override',
                'verbose_name_plural': 'Feature Flag Overrides',
                'db_table': 'feature_flag_overrides',
            },
        ),
        migrations.AddIndex(
            model_name='featureflag',
            index=models.Index(fields=['key', 'is_active'], name='feature_fla_key_352420_idx'),
        ),
        migrations.AddIndex(
            model_name='featureflag',
            index=models.Index(fields=['category'], name='feature_fla_categor_fb8e88_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='featureflagoverride',
            unique_together={('flag', 'studio'), ('flag', 'user')},
        ),
    ]
