# Generated by Django 5.2.15 on 2026-06-19 16:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0006_subscriptionplan_subscription"),
        ("core", "0017_user_is_approved"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("venue", models.CharField(max_length=200)),
                ("scheduled_start", models.DateTimeField()),
                ("scheduled_end", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("pending_approval", "Pending Approval"),
                            ("assigned", "Assigned"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("pay_rate", models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                (
                    "pay_type",
                    models.CharField(
                        choices=[("flat", "Flat Rate"), ("hourly", "Hourly Rate")],
                        default="flat",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "band",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gigs",
                        to="core.band",
                    ),
                ),
                (
                    "studio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gigs",
                        to="core.studio",
                    ),
                ),
            ],
            options={
                "db_table": "gigs",
                "ordering": ["-scheduled_start"],
            },
        ),
        migrations.CreateModel(
            name="GigClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Notes from the band leader")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "band",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gig_claims",
                        to="core.band",
                    ),
                ),
                (
                    "gig",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="gigs.gig",
                    ),
                ),
            ],
            options={
                "db_table": "gig_claims",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GigPayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "band",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="core.band",
                    ),
                ),
                (
                    "gig",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout",
                        to="gigs.gig",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gig_payouts",
                        to="billing.payment",
                    ),
                ),
            ],
            options={
                "db_table": "gig_payouts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BandAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "month",
                    models.DateField(
                        help_text="Normalized to first day of the month (e.g. 2026-07-01)"
                    ),
                ),
                (
                    "availability_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Structured availability JSON"
                    ),
                ),
                ("is_submitted", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "band",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="core.band",
                    ),
                ),
            ],
            options={
                "db_table": "band_availabilities",
                "ordering": ["-month", "band__name"],
                "unique_together": {("band", "month")},
            },
        ),
        migrations.AddIndex(
            model_name="gig",
            index=models.Index(fields=["status"], name="gigs_status_2033ad_idx"),
        ),
        migrations.AddIndex(
            model_name="gig",
            index=models.Index(fields=["scheduled_start"], name="gigs_schedul_169404_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="gigclaim",
            unique_together={("gig", "band")},
        ),
    ]
